services:
  - type: web
    name: freespot-ml-api
    env: docker
    dockerfilePath: ./Dockerfile
    region: singapore
    plan: free
    envVars:
      - key: YOLO_MODEL
        value: yolov8n.pt
      - key: PORT
        value: 10000
    healthCheckPath: /health
